### ISSUE TITLE
由于 nhentai API 无限期关停，此项目暂定停止维护

### ISSUE THREAD

**Issue by Tsuk1ko** [Tsuk1ko/nhder#1]
https://twitter.com/fuckmaou/status/1084550608097603585

nhentai 网站所有者在推特称，大量第三方 APP 对开放 API 的使用导致了带宽问题，今后可能会转为需要 api key 的形式

尊重站点所有者的意见，该项目如果被不正当使用有使问题恶化的可能性，因此在有新进展前，这个问题的最终解决方案我也不会在项目中更新，转为我个人自用

**Comment by Kadantte** [comment]
https://twitter.com/fuckmaou/status/1113868849500303363
The API is back again.

**Comment by Tsuk1ko** [comment]
Great!
